user.name.get:
  path: /user/name/{username}
  controller: App\Controller\UserController::loadUserByUsername
  methods: [GET]

user.get:
  path: /user/{id}
  controller: App\Controller\UserController::loadUserById
  methods: [GET]

user.update:
  path: /user/{id}
  controller: App\Controller\UserController::updateUser
  methods: [PUT]

register.user:
  path: /register/user
  controller: App\Controller\UserController::addUser
  methods: [POST]


